### PR TITLE
feat(HACBS-1261): add pyxis/create_container_image to PATH

### PR DESCRIPTION
**Pull request by johnbieren**
This commit adds the create_container_image script to PATH
Signed-off-by: Johnny Bieren <jbieren@redhat.com>

### CODE REVIEW

**Review by happybhati — APPROVED** [review]

**Comment by mmalina** [comment]
Nit: The script was already executable (+x), we're just adding it to PATH here. So I would recommend changing the commit message slightly for that.

**Review by davidmogar — COMMENTED** [review]
This change mixes two different things. I would split them in two commits at least.

**Comment by johnbieren** [comment]
Opened https://github.com/hacbs-release/release-utils/pull/15 and changed the commit based on feedback

**Comment by mmalina** [comment]
OK, LGTM!

**Review by mmalina — APPROVED** [review]

**Pull request merged**
